# This is a config for E2B sandbox template.
# You can use template ID (nnwt1o5wf494uyjrfwor) or template name (manit-techin-linktree-1) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("manit-techin-linktree-1") # Sync sandbox
# sandbox = await AsyncSandbox.create("manit-techin-linktree-1") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('manit-techin-linktree-1')

team_id = "edfae4fe-b0e5-4d8b-97f5-e2cbfb575873"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "manit-techin-linktree-1"
template_id = "nnwt1o5wf494uyjrfwor"
